CREATE TABLE Users (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    username VARCHAR(20) UNIQUE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Documents (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id INTEGER,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE DocumentVersions (
    id INTEGER NOT NULL AUTO_INCREMENT,
    document_id INTEGER,
    modification_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    route VARCHAR(100),
    PRIMARY KEY (id),
    FOREIGN KEY (document_id) REFERENCES Documents(id) ON DELETE CASCADE
);
